name: Crypto Alerts

on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:  

jobs:
  send-alerts:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run crypto alerts
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
      run: python crypto_alerts.py
